Add storybook for SafeNote
glucoseinc/naumanni pull request #16
Opened 2017-05-22 09:59 UTC by pe-ter-

2017-05-22 13:57 UTC, shnjp requested changes
javascript足して、実行されないテストを追加して下さい。

2017-05-23 02:19 UTC, pe-ter- commented
> javascript足して

すいません、ちょっと伝わらなかったです

> 実行されないテストを追加して下さい

jestも一緒に書くということですか？)

2017-05-23 02:23 UTC, shnjp commented
や、単純に

```<script>alert('hope')</script>```

みたいな、contentを突っ込んでも、問題が発生しないよね。的なテストです

2017-05-23 02:26 UTC, pe-ter- commented
了解です 🙌

2017-05-23 02:40 UTC, pe-ter- commented
足しました

2017-05-23 05:49 UTC, merged